/* holo3d.js — real-time 3D scenes for every Lumen8 illustration.
   Each <canvas data-holo="name"> gets its own lit Three.js scene: solid
   materials with emissive edges, glass solar modules, terrain, water, glowing
   flows and labels. Drag to orbit, hover to tilt, auto-rotates when idle.
   Layered scenes (pipelines) expose Holo.setStep(canvas, i). Requires THREE. */
(function () {
  'use strict';
  if (typeof THREE === 'undefined') return;
  const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const P = { blue: 0x3b82f6, blue2: 0x60a5fa, cyan: 0x22d3ee, cyan2: 0x67e8f9, violet: 0xa78bfa, green: 0x34d399, rose: 0xfb7185, ink: 0xeaf0f8, slate: 0x111a2e, deep: 0x0a1424, bg: 0x04060c };
  const V3 = (x, y, z) => new THREE.Vector3(x, y, z);

  /* ---------- shared resources ---------- */
  const glowTex = (() => { const c = document.createElement('canvas'); c.width = c.height = 64; const x = c.getContext('2d'); const g = x.createRadialGradient(32, 32, 0, 32, 32, 32); g.addColorStop(0, 'rgba(255,255,255,1)'); g.addColorStop(.35, 'rgba(255,255,255,.5)'); g.addColorStop(1, 'rgba(255,255,255,0)'); x.fillStyle = g; x.fillRect(0, 0, 64, 64); return new THREE.CanvasTexture(c); })();
  const solid = (color, emissive, ei, opacity) => new THREE.MeshStandardMaterial({ color, emissive: emissive == null ? color : emissive, emissiveIntensity: ei == null ? .08 : ei, metalness: .55, roughness: .4, transparent: opacity != null, opacity: opacity == null ? 1 : opacity });
  const glass = (color) => new THREE.MeshStandardMaterial({ color: 0x2563eb, emissive: color, emissiveIntensity: .55, metalness: .85, roughness: .12, transparent: true, opacity: .95 });
  const edgeMat = (color, opacity) => new THREE.LineBasicMaterial({ color, transparent: true, opacity: opacity == null ? .7 : opacity, blending: THREE.AdditiveBlending, depthWrite: false });
  const sprite = (color, size, opacity) => { const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: glowTex, color, transparent: true, opacity: opacity == null ? 1 : opacity, blending: THREE.AdditiveBlending, depthWrite: false })); s.scale.set(size, size, 1); return s; };
  const hash = (x, y) => { const s = Math.sin(x * 127.1 + y * 311.7) * 43758.5453; return s - Math.floor(s); };
  const lerp = (a, b, t) => a + (b - a) * t, sm = (t) => t * t * (3 - 2 * t);
  const noise = (x, y) => { const ix = Math.floor(x), iy = Math.floor(y), fx = sm(x - ix), fy = sm(y - iy); return lerp(lerp(hash(ix, iy), hash(ix + 1, iy), fx), lerp(hash(ix, iy + 1), hash(ix + 1, iy + 1), fx), fy); };
  const fbm = (x, z, amp, freq) => { let h = 0, a = amp, f = freq; for (let o = 0; o < 4; o++) { h += (noise(x * f + 11, z * f + 7) - .5) * a; a *= .5; f *= 2.1; } return h; };
  const rnd = (s) => () => { s = (s * 9301 + 49297) % 233280; return s / 233280; };

  /* ---------- kit ---------- */
  const K = {}; const V = V3;
  K.box = (w, h, d, mat, edge, eo) => { const g = new THREE.Group(); const m = new THREE.Mesh(new THREE.BoxGeometry(w, h, d), mat); m.position.y = h / 2; g.add(m); if (edge) { const e = new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry), edgeMat(edge, eo)); e.position.y = h / 2; g.add(e); } return g; };
  K.grid = (size, div, color, opacity) => { const g = new THREE.GridHelper(size, div, color, color); g.material.transparent = true; g.material.opacity = opacity == null ? .12 : opacity; g.material.depthWrite = false; return g; };
  K.terrain = (size, seg, amp, freq, color, wire) => { const g = new THREE.Group(); const geo = new THREE.PlaneGeometry(size, size, seg, seg); geo.rotateX(-Math.PI / 2); const p = geo.attributes.position; for (let i = 0; i < p.count; i++) { const x = p.getX(i), z = p.getZ(i); p.setY(i, fbm(x, z, amp, freq) - amp * .1); } geo.computeVertexNormals(); g.add(new THREE.Mesh(geo, new THREE.MeshStandardMaterial({ color: color || P.deep, metalness: .3, roughness: .85, polygonOffset: true, polygonOffsetFactor: 1 }))); if (wire !== false) g.add(new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ color: P.cyan, wireframe: true, transparent: true, opacity: .07, depthWrite: false }))); g.userData.h = (x, z) => fbm(x, z, amp, freq) - amp * .1; return g; };
  K.pv = (rows, cols, px, pz, color) => { const g = new THREE.Group(); const n = rows * cols; const mod = new THREE.InstancedMesh(new THREE.BoxGeometry(px * .86, .06, pz * .62), glass(color || P.blue), n); const frame = new THREE.InstancedMesh(new THREE.BoxGeometry(px * .88, .1, pz * .64), new THREE.MeshStandardMaterial({ color: 0xbfdbfe, emissive: 0x93c5fd, emissiveIntensity: .4, metalness: .9, roughness: .3, wireframe: true, transparent: true, opacity: .55 }), n); const post = new THREE.InstancedMesh(new THREE.CylinderGeometry(.06, .06, 1.2, 6), solid(0x9fb3c8, 0x000000, 0), n); const m = new THREE.Matrix4(), q = new THREE.Quaternion().setFromEuler(new THREE.Euler(-.35, 0, 0)), s = new THREE.Vector3(1, 1, 1); let k = 0; for (let i = 0; i < rows; i++) for (let j = 0; j < cols; j++) { const x = (j - (cols - 1) / 2) * px, z = (i - (rows - 1) / 2) * pz; m.compose(V3(x, 1.3, z), q, s); mod.setMatrixAt(k, m); frame.setMatrixAt(k, m); m.compose(V3(x, .6, z), new THREE.Quaternion(), s); post.setMatrixAt(k, m); k++; } g.add(mod, frame, post); g.userData.mod = mod; return g; };
  K.house = (w, d, h, r) => { const g = new THREE.Group(); const body = K.box(w, h, d, new THREE.MeshStandardMaterial({ color: 0x8e9bb3, metalness: .05, roughness: .9, emissive: 0x1e3a8a, emissiveIntensity: .12 }), 0xeaf0f8, .28); g.add(body); const roof = new THREE.Mesh(new THREE.ConeGeometry(Math.hypot(w, d) * .55, h * .45, 4), new THREE.MeshStandardMaterial({ color: 0x1b2438, metalness: .2, roughness: .85, emissive: 0x1e3a8a, emissiveIntensity: .1 })); roof.position.y = h + h * .225; roof.rotation.y = Math.PI / 4; g.add(roof); const re = new THREE.LineSegments(new THREE.EdgesGeometry(roof.geometry), edgeMat(0xbfdbfe, .22)); re.position.copy(roof.position); re.rotation.copy(roof.rotation); g.add(re); const win = new THREE.Mesh(new THREE.PlaneGeometry(w * .22, h * .3), new THREE.MeshBasicMaterial({ color: 0xbfdbfe, transparent: true, opacity: .0 })); win.position.set(0, h * .5, d / 2 + .03); g.add(win); g.userData.win = win; g.rotation.y = r * Math.PI; return g; };
  K.ring = (radius, color, w) => { const m = new THREE.Mesh(new THREE.RingGeometry(radius * (1 - (w || .03)), radius, 96), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .8, side: THREE.DoubleSide, blending: THREE.AdditiveBlending, depthWrite: false })); m.rotation.x = -Math.PI / 2; return m; };
  K.beam = (h, color) => { const g = new THREE.Group(); const b = new THREE.Mesh(new THREE.CylinderGeometry(.12, .5, h, 12, 1, true), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .55, blending: THREE.AdditiveBlending, depthWrite: false })); b.position.y = h / 2; g.add(b); const halo = new THREE.Mesh(new THREE.CylinderGeometry(.6, 1.6, h, 12, 1, true), new THREE.MeshBasicMaterial({ color, transparent: true, opacity: .12, blending: THREE.AdditiveBlending, depthWrite: false, side: THREE.DoubleSide })); halo.position.y = h / 2; g.add(halo); g.add(sprite(color, 6, .9)); const light = new THREE.PointLight(color, 3, 60, 1.6); light.position.y = 2; g.add(light); g.userData.mat = b.material; return g; };
  K.line = (pts, color, opacity, dashed) => { const geo = new THREE.BufferGeometry().setFromPoints(pts.map((p) => Array.isArray(p) ? V3(...p) : p)); const mat = dashed ? new THREE.LineDashedMaterial({ color, dashSize: 1.2, gapSize: .9, transparent: true, opacity: opacity == null ? .7 : opacity }) : edgeMat(color, opacity == null ? .7 : opacity); const l = new THREE.Line(geo, mat); if (dashed) l.computeLineDistances(); return l; };
  K.flow = (pts, color, n, speed) => { const g = new THREE.Group(); const curve = new THREE.CatmullRomCurve3(pts.map((p) => Array.isArray(p) ? V3(...p) : p)); g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(curve.getPoints(48)), edgeMat(color, .45))); const parts = []; for (let i = 0; i < (n || 3); i++) { const s = sprite(color, 1.6, .95); g.add(s); parts.push({ s, u: i / (n || 3) }); } g.userData.tick = (dt) => { parts.forEach((p) => { p.u = (p.u + dt * (speed || .25)) % 1; curve.getPointAt(p.u, p.s.position); p.s.material.opacity = .3 + .7 * Math.sin(p.u * Math.PI); }); }; return g; };
  K.label = (text, color) => { const c = document.createElement('canvas'); c.width = 512; c.height = 64; const x = c.getContext('2d'); x.font = '500 30px "JetBrains Mono", monospace'; x.fillStyle = color || '#67e8f9'; x.textBaseline = 'middle'; x.letterSpacing = '3px'; x.fillText(text, 8, 32); const t = new THREE.CanvasTexture(c); t.minFilter = THREE.LinearFilter; const s = new THREE.Sprite(new THREE.SpriteMaterial({ map: t, transparent: true, depthWrite: false })); s.scale.set(16, 2, 1); s.center.set(0, .5); return s; };
  K.bars = (vals, color, gap) => { const g = new THREE.Group(); const list = []; vals.forEach((v, i) => { const b = K.box(1.4, v, 1.4, solid(color, color, .35, .9), color, .5); b.position.x = i * (gap || 2.2); g.add(b); list.push({ b, v }); }); g.userData.tick = (t) => list.forEach((o, i) => { const s = .82 + .18 * Math.sin(t * 1.2 + i * .7); o.b.scale.y = s; }); return g; };
  K.docs = () => { const g = new THREE.Group(); for (let i = 0; i < 3; i++) { const d = K.box(7, .25, 9.5, solid(0x0e1628, 0x1e3a8a, i === 2 ? .35 : .12), i === 2 ? P.cyan2 : 0x9fb3c8, i === 2 ? .8 : .3); d.position.set(i * .9, i * .5, -i * .9); g.add(d); } for (let k = 0; k < 4; k++) g.add(K.line([[-1.4, 1.75, -4.6 + k * 1.6], [k === 3 ? 1.6 : 3.6, 1.75, -4.6 + k * 1.6]], P.cyan2, .9)); const ok = sprite(P.green, 3.5, .9); ok.position.set(3.4, 1.9, 3.4); g.add(ok); return g; };
  K.water = (size, color) => { const geo = new THREE.PlaneGeometry(size, size, 48, 48); geo.rotateX(-Math.PI / 2); const m = new THREE.Mesh(geo, new THREE.MeshStandardMaterial({ color: color || 0x0b2a3d, metalness: .85, roughness: .2, transparent: true, opacity: .95 })); const w = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({ color: P.cyan, wireframe: true, transparent: true, opacity: .06, depthWrite: false })); const g = new THREE.Group(); g.add(m, w); const p = geo.attributes.position, base = p.array.slice(); g.userData.tick = (t) => { for (let i = 0; i < p.count; i++) { const x = base[i * 3], z = base[i * 3 + 2]; p.setY(i, Math.sin(x * .25 + t * 1.1) * .18 + Math.sin(z * .32 - t * .8) * .14); } p.needsUpdate = true; geo.computeVertexNormals(); }; return g; };
  K.crane = (color) => { const g = new THREE.Group(); const legMat = solid(0x9fb3c8, 0x000000, 0); [[-2.2, -1.4], [2.2, -1.4], [-2.2, 1.4], [2.2, 1.4]].forEach(([x, z]) => { const l = new THREE.Mesh(new THREE.BoxGeometry(.35, 14, .35), legMat); l.position.set(x, 7, z); g.add(l); }); const boom = K.box(3.6, .45, 18, solid(0x1a2438, color, .35), color, .8); boom.position.set(0, 14, 5); g.add(boom); const cab = K.box(1.8, 1.4, 1.8, solid(0x1a2438, color, .2), color, .6); cab.position.set(0, 11.6, 4); g.add(cab); const cable = K.line([[0, 14, 10], [0, 4.5, 10]], color, .6); g.add(cable); g.userData.cable = cable; return g; };
  K.ship = () => { const g = new THREE.Group(); const sh = new THREE.Shape(); sh.moveTo(-14, -3.2); sh.lineTo(10, -3.2); sh.quadraticCurveTo(16, 0, 10, 3.2); sh.lineTo(-14, 3.2); sh.lineTo(-14, -3.2); const hull = new THREE.Mesh(new THREE.ExtrudeGeometry(sh, { depth: 2.6, bevelEnabled: false }), solid(0x141c2e, 0x1e3a8a, .12)); hull.rotation.x = -Math.PI / 2; hull.position.y = 0; g.add(hull); const he = new THREE.LineSegments(new THREE.EdgesGeometry(hull.geometry), edgeMat(0xc7d2e0, .35)); he.rotation.copy(hull.rotation); g.add(he); const cols = [P.blue, P.cyan, P.violet, P.green, P.blue2]; for (let i = 0; i < 8; i++) for (let j = 0; j < 2; j++) for (let k = 0; k < (i % 3 === 0 ? 2 : 3); k++) { const c = K.box(2.4, 1.1, 2.4, solid(cols[(i + j + k) % 5], cols[(i + j + k) % 5], .2), null); c.position.set(-12 + i * 2.7, 2.6 + k * 1.1, -1.4 + j * 2.7); g.add(c); } const bridge = K.box(2.4, 3.4, 5.2, solid(0xd6e0ec, 0x2a3650, .05), 0xffffff, .3); bridge.position.set(-12.6, 2.6, 0); g.add(bridge); return g; };
  K.tower = (h, color) => { const pts = []; const legs = [[-1.6, -1.6], [1.6, -1.6], [1.6, 1.6], [-1.6, 1.6]]; const at = (l, t) => V3(legs[l][0] * (1 - t * .8), h * t, legs[l][1] * (1 - t * .8)); for (let l = 0; l < 4; l++) { pts.push(at(l, 0), at(l, 1)); for (let s = 0; s < 9; s++) { const t0 = s / 9, t1 = (s + 1) / 9, n = (l + 1) % 4; pts.push(at(l, t0), at(n, t0), at(l, t0), at(n, t1)); } } const g = new THREE.Group(); g.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(pts), edgeMat(color, .85))); const mast = new THREE.Mesh(new THREE.CylinderGeometry(.08, .08, 3, 6), solid(color, color, .6)); mast.position.y = h + 1.5; g.add(mast); const ant = [K.box(.3, 1.6, .12, solid(0xd6e0ec, color, .2)), K.box(.3, 1.6, .12, solid(0xd6e0ec, color, .2)), K.box(.3, 1.6, .12, solid(0xd6e0ec, color, .2))]; ant.forEach((a, i) => { const an = i * 2.09; a.position.set(Math.cos(an) * .9, h - 1.4, Math.sin(an) * .9); a.rotation.y = -an; g.add(a); }); return g; };

  /* ---------- scenes ---------- */
  const S = {};
  S.village = () => { const r = rnd(7), root = new THREE.Group(), L = [root]; const T = K.terrain(140, 80, 1.6, .05); root.add(T, K.grid(140, 56, P.cyan, .07)); const hs = []; for (let i = 0; i < 18; i++) { const a = r() * 6.28, d = 6 + r() * 20, x = Math.cos(a) * d, z = Math.sin(a) * d * .75; const h = K.house(3.2 + r() * 1.8, 2.6 + r() * 1.4, 1.1 + r() * .4, r()); h.position.set(x, T.userData.h(x, z), z); root.add(h); hs.push(h); } const road = []; for (let i = 0; i <= 30; i++) { const x = -32 + i * 2.1, z = Math.sin(i * .35) * 6; road.push(V3(x, T.userData.h(x, z) + .08, z)); } root.add(K.line(road, 0x8fa3bd, .35)); const pv = K.pv(4, 4, 2.2, 1.7, P.blue); pv.position.set(20, T.userData.h(20, 12), 12); root.add(pv); const hub = V3(20, T.userData.h(20, 12) + 1.5, 12); const flows = []; hs.forEach((h) => { const f = K.flow([hub, V3(h.position.x, h.position.y + 1.6, h.position.z)], P.cyan2, 1, .12 + r() * .1); root.add(f); flows.push(f); }); const beam = K.beam(24, P.blue2); beam.position.y = T.userData.h(0, 0); root.add(beam); const rings = [K.ring(1, P.blue2), K.ring(1, P.blue2), K.ring(1, P.cyan)]; rings.forEach((rg) => { rg.position.y = T.userData.h(0, 0) + .15; root.add(rg); }); const lb = K.label('481 HOUSEHOLDS · TIER A', '#93c5fd'); lb.position.set(1.5, 9, 0); root.add(lb); return { layers: L, radius: 27, tick(t, dt) { flows.forEach((f) => f.userData.tick(dt)); rings.forEach((rg, i) => { const ph = (t * .35 + i * .33) % 1; rg.scale.setScalar(1 + ph * 16); rg.material.opacity = (1 - ph) * .7; }); hs.forEach((h, i) => { h.userData.win.material.opacity = .35 + .35 * Math.sin(t * 1.5 + i); }); } }; };
  S.plant = () => { const root = new THREE.Group(), L = [root]; const T = K.terrain(200, 80, 1.2, .03, 0x0b1626); root.add(T, K.grid(200, 66, P.cyan, .06)); for (let bx = 0; bx < 3; bx++) for (let bz = 0; bz < 2; bz++) { const pv = K.pv(7, 6, 2.2, 1.9, P.blue); pv.position.set(-30 + bx * 30, .2, -16 + bz * 24); root.add(pv); const inv = K.box(2.2, 1.6, 1.4, solid(0xd6e0ec, P.cyan, .3), P.cyan, .8); inv.position.set(-30 + bx * 30 + 8, .1, -16 + bz * 24 + 8); root.add(inv); } root.add(K.line([[-46, .2, -30], [46, .2, -30], [46, .2, 26], [-46, .2, 26], [-46, .2, -30]], P.blue2, .55, true)); root.add(K.line([[-46, .25, 3], [46, .25, 3]], 0x8fa3bd, .35), K.line([[0, .25, -30], [0, .25, 26]], 0x8fa3bd, .35)); const sub = K.box(7, 4, 5, solid(0x1a2438, P.cyan, .25), P.cyan2, .8); sub.position.set(36, .1, 32); root.add(sub); const tr = K.box(2.6, 2.6, 2.6, solid(0x9fb3c8, P.blue, .2), P.blue2, .6); tr.position.set(30, .1, 33); root.add(tr); const mv = K.flow([[39, 4, 32], [50, 14, 20], [60, 22, 4], [66, 26, -12]], P.cyan, 5, .18); root.add(mv); const pylon = K.tower(26, 0xc7d2e0); pylon.position.set(66, .1, -12); root.add(pylon); const lb = K.label('6,492 ROWS · 200 MWp', '#93c5fd'); lb.position.set(-44, 7, -34); root.add(lb); const lb2 = K.label('SUBSTATION', '#67e8f9'); lb2.position.set(36, 7, 32); root.add(lb2); return { layers: L, radius: 52, tick(t, dt) { mv.userData.tick(dt); } }; };
  S.port = () => { const root = new THREE.Group(), L = [root]; const water = K.water(110); root.add(water); const quay = K.box(80, 3.4, 22, solid(0x2a3446, 0x1e3a8a, .1), 0xc7d2e0, .45); quay.position.set(0, -.2, -18); root.add(quay); root.add(K.line([[-40, 3.3, -7], [40, 3.3, -7]], P.cyan2, .5)); const cranes = [-22, -4, 14].map((x) => { const c = K.crane(P.cyan); c.position.set(x, 3.2, -14); root.add(c); return c; }); const ship = K.ship(); ship.position.set(2, .2, 4); root.add(ship); for (let i = 0; i < 6; i++) for (let j = 0; j < 3; j++) { const b = K.box(2.4, 1.1, 2.4, solid([P.blue, P.violet, P.cyan][(i + j) % 3], [P.blue, P.violet, P.cyan][(i + j) % 3], .18)); b.position.set(-30 + i * 3.2, 3.2, -24 + j * 2.8); root.add(b); } const sp = K.box(4.6, 4, 3.4, solid(0x1a2438, P.cyan, .3), P.cyan2, .9); sp.position.set(-36, 3.2, -14); root.add(sp); const beam = K.beam(18, P.cyan); beam.position.set(-36, 7.2, -14); root.add(beam); const cable = K.flow([[-34, 5.5, -13], [-24, 4.8, -6], [-13, 4.2, 1]], P.blue2, 3, .2); root.add(cable); const lb = K.label('SHORE POWER · 1,840 kW AT BERTH', '#67e8f9'); lb.position.set(-38, 12, -14); root.add(lb); return { layers: L, radius: 54, tick(t, dt) { water.userData.tick(t); cable.userData.tick(dt); ship.position.y = .2 + Math.sin(t * .8) * .12; ship.rotation.z = Math.sin(t * .6) * .006; } }; };
  S.tower = () => { const root = new THREE.Group(), L = [root]; const T = K.terrain(120, 60, 1.4, .06); root.add(T, K.grid(120, 48, P.rose, .05)); const tw = K.tower(22, P.rose); root.add(tw); const rings = [K.ring(1, P.rose, .02), K.ring(1, P.rose, .02), K.ring(1, P.rose, .02)]; rings.forEach((r) => { r.position.y = 22; root.add(r); }); const pv = K.pv(3, 4, 2.2, 1.7, P.blue); pv.position.set(-13, T.userData.h(-13, 8), 8); root.add(pv); const shelter = K.box(3.2, 2.4, 2.6, solid(0x1a2438, P.cyan, .25), P.cyan2, .8); shelter.position.set(-4, T.userData.h(-4, 8), 8); root.add(shelter); const gen = K.box(3, 1.8, 1.8, solid(0x2a1a22, P.rose, .25), P.rose, .6); gen.position.set(9, T.userData.h(9, 9), 9); root.add(gen); const fl = K.flow([[-8, 2, 8], [-5, 1.8, 8]], P.blue2, 2, .3); root.add(fl); const lb = K.label('SITE FIT 81 · DIESEL -82%', '#fda4af'); lb.position.set(4, 5, 12); root.add(lb); return { layers: L, radius: 30, tick(t, dt) { rings.forEach((r, i) => { const ph = (t * .4 + i * .33) % 1; r.scale.setScalar(1 + ph * 22); r.material.opacity = (1 - ph) * .6; }); fl.userData.tick(dt); } }; };
  S.fields = () => { const r = rnd(3), root = new THREE.Group(), L = [root]; const T = K.terrain(160, 60, .8, .04, 0x0a1a1a); root.add(T); const cols = [P.green, P.blue, P.cyan, 0x2dd4bf, P.violet]; for (let i = -3; i < 3; i++) for (let j = -2; j < 3; j++) { const x = i * 13 + r() * 3, z = j * 12 + r() * 3, c = cols[(i * 5 + j + 40) % 5]; const sh = new THREE.Shape(); sh.moveTo(0, 0); sh.lineTo(11 + r() * 2, r() * 2); sh.lineTo(10.5, 10 + r() * 2); sh.lineTo(-r() * 1.5, 10.5); const m = new THREE.Mesh(new THREE.ShapeGeometry(sh), new THREE.MeshStandardMaterial({ color: c, emissive: c, emissiveIntensity: .12, transparent: true, opacity: .32, roughness: .9, side: THREE.DoubleSide })); m.rotation.x = -Math.PI / 2; m.position.set(x, T.userData.h(x, z) + .25, z); root.add(m); const e = new THREE.LineSegments(new THREE.EdgesGeometry(m.geometry), edgeMat(c, .6)); e.rotation.copy(m.rotation); e.position.copy(m.position); root.add(e); if (r() > .5) for (let k = 1; k < 5; k++) root.add(K.line([[x + 1, T.userData.h(x, z) + .3, z + k * 2], [x + 9.5, T.userData.h(x, z) + .3, z + k * 2]], c, .25)); } const pv = K.pv(3, 4, 2.2, 1.7, P.blue); pv.position.set(-8, .8, -6); root.add(pv); const pump = K.box(2.4, 2.2, 2.4, solid(0x1a2438, P.cyan, .3), P.cyan2, .8); pump.position.set(9, .6, -3); root.add(pump); const beam = K.beam(14, P.cyan); beam.position.set(9, 2.8, -3); root.add(beam); const fl = K.flow([[-3, 1.8, -6], [8, 1.8, -3]], P.blue2, 2, .25); root.add(fl); const lb = K.label('RICE 12% · TREE CROP 46% · PUMP 18 kW', '#6ee7b7'); lb.position.set(-36, 6, -30); root.add(lb); return { layers: L, radius: 44, tick(t, dt) { fl.userData.tick(dt); } }; };
  S.graph = () => { const r = rnd(11), root = new THREE.Group(), L = [root]; const strata = [[P.rose, 6, 6, 30], [P.green, 12, 24, 22], [P.blue2, 18, 34, 15], [P.cyan2, 26, 52, 8], [P.violet, 36, 70, 1]]; const nodes = []; strata.forEach(([c, rad, n, y]) => { const ring = K.ring(rad + 4, c, .008); ring.position.y = y; ring.material.opacity = .3; root.add(ring); const pts = []; for (let i = 0; i < n; i++) { const a = r() * 6.28, d = rad * (.35 + r() * .65), p = V3(Math.cos(a) * d, y + (r() - .5) * 1.5, Math.sin(a) * d); nodes.push({ p, c }); pts.push(p); } const pg = new THREE.BufferGeometry().setFromPoints(pts); root.add(new THREE.Points(pg, new THREE.PointsMaterial({ color: c, size: 1.3, map: glowTex, transparent: true, opacity: .95, blending: THREE.AdditiveBlending, depthWrite: false }))); }); const ep = []; for (let i = 0; i < 140; i++) { const a = nodes[(r() * nodes.length) | 0], b = nodes[(r() * nodes.length) | 0]; if (a !== b && Math.abs(a.p.y - b.p.y) < 16) ep.push(a.p, b.p); } root.add(new THREE.LineSegments(new THREE.BufferGeometry().setFromPoints(ep), edgeMat(P.violet, .16))); const pulses = []; for (let i = 0; i < 10; i++) { const s = sprite(P.cyan2, 1.4, .9); root.add(s); pulses.push({ s, i: (r() * (ep.length / 2)) | 0, u: r() }); } root.add(K.grid(80, 20, P.violet, .05)); const lb = K.label('18,413 NODES · 94,226 EDGES', '#c4b5fd'); lb.position.set(-36, 34, 0); root.add(lb); return { layers: L, radius: 40, spin: .3, tick(t, dt) { pulses.forEach((p) => { p.u += dt * .5; if (p.u > 1) { p.u = 0; p.i = (Math.random() * (ep.length / 2)) | 0; } const a = ep[p.i * 2], b = ep[p.i * 2 + 1]; if (a && b) p.s.position.lerpVectors(a, b, p.u); }); } }; };
  S.geo = () => { const root = new THREE.Group(), L = [root]; const D = 16, lay = [[0, -6, 0x24304a, .18], [-6, -14, 0x2a2f55, .22], [-14, -26, 0x4a2140, .3], [-26, -40, 0x5a1a2e, .4]]; lay.forEach(([y0, y1, c, e]) => { const m = K.box(60, y0 - y1, D, new THREE.MeshStandardMaterial({ color: c, emissive: c, emissiveIntensity: e, metalness: .2, roughness: .85, transparent: true, opacity: .95 }), 0xbfdbfe, .35); m.position.y = y1; root.add(m); root.add(K.line([[-30, y1, D / 2 + .05], [30, y1, D / 2 + .05]], 0xbfdbfe, .5)); }); const top = K.terrain(60, 40, 1.6, .06, 0x16213a); top.scale.z = D / 60; root.add(top); const hot = new THREE.Mesh(new THREE.SphereGeometry(9, 24, 16), new THREE.MeshBasicMaterial({ color: P.rose, transparent: true, opacity: .16, blending: THREE.AdditiveBlending, depthWrite: false })); hot.position.set(2, -34, 0); hot.scale.set(1.6, .7, 1); root.add(hot); [-10, 12].forEach((x) => { root.add(K.line([[x, 2.5, D / 2 + .1], [x, -30, D / 2 + .1]], 0xffffff, .9)); const head = K.box(2.2, 1.6, 1.6, solid(0xd6e0ec, P.blue, .3), P.blue2, .8); head.position.set(x, top.userData.h(x, 0) + .3, D / 2 - .8); root.add(head); const tip = sprite(P.blue2, 4, .9); tip.position.set(x, -30, D / 2 + .2); root.add(tip); }); const plume = []; for (let i = 0; i < 46; i++) { const s = sprite(i % 3 ? P.rose : P.violet, 1.4 + Math.random() * 1.4, .8); s.position.set(-18 + Math.random() * 36, -40 + Math.random() * 30, D / 2 + .3); root.add(s); plume.push({ s, v: .8 + Math.random() * 1.2, x0: s.position.x }); } const bars = K.bars([4, 9, 14], P.blue, 2.6); bars.position.set(-26, 2.5, -4); root.add(bars); const lb = K.label('P90 · P50 · P10  ·  PLAY FAIRWAY 0.74', '#93c5fd'); lb.position.set(-28, 19, -4); root.add(lb); return { layers: L, radius: 38, pitch: .32, spin: .05, theta: .25, tick(t, dt) { plume.forEach((p) => { p.s.position.y += dt * p.v * 3; p.s.position.x = p.x0 + Math.sin(t + p.x0) * 1.5; if (p.s.position.y > -8) p.s.position.y = -40; p.s.material.opacity = .2 + .6 * ((p.s.position.y + 40) / 32); }); bars.userData.tick(t); } }; };
  S.nodes = () => { const root = new THREE.Group(), L = [root]; root.add(K.grid(80, 20, P.violet, .06)); const hex = []; for (let i = 0; i < 6; i++) { const a = i * Math.PI / 3; hex.push(V3(Math.cos(a) * 22, 4 + (i % 2) * 5, Math.sin(a) * 22)); } const core = new THREE.Mesh(new THREE.IcosahedronGeometry(3, 1), new THREE.MeshStandardMaterial({ color: P.violet, emissive: P.violet, emissiveIntensity: .6, metalness: .6, roughness: .3, wireframe: true })); core.position.y = 10; root.add(core); root.add(sprite(P.violet, 14, .5)).position.y = 10; const flows = []; hex.forEach((p, i) => { const n = new THREE.Mesh(new THREE.OctahedronGeometry(1.6, 0), solid(P.violet, P.violet, .5)); n.position.copy(p); root.add(n); root.add(K.line([p, hex[(i + 1) % 6]], P.violet, .45)); const f = K.flow([p, V3(0, 10, 0)], P.cyan2, 2, .2); root.add(f); flows.push(f); const b = K.beam(p.y, P.violet); b.position.set(p.x, 0, p.z); b.userData.mat.opacity = .25; root.add(b); }); return { layers: L, radius: 30, tick(t, dt) { core.rotation.y = t * .4; core.rotation.x = t * .2; flows.forEach((f) => f.userData.tick(dt)); } }; };
  S['pipe-home'] = () => { const r = rnd(5), L = [], mk = () => { const g = new THREE.Group(); L.push(g); return g; }; const T = K.terrain(170, 90, 2.2, .04); const L0 = mk(); L0.add(T, K.grid(170, 56, P.cyan, .06)); const beam = K.beam(30, P.blue2); beam.position.y = T.userData.h(0, 0); L0.add(beam); const rings = [K.ring(1, P.blue2), K.ring(1, P.blue2), K.ring(1, P.cyan)]; rings.forEach((rg) => { rg.position.y = T.userData.h(0, 0) + .2; L0.add(rg); }); const lb0 = K.label('-8.6427, 120.0132', '#93c5fd'); lb0.position.set(1.5, 12, 0); L0.add(lb0);
    const L1 = mk(); for (let k = 0; k < 6; k++) { const p = []; for (let i = 0; i <= 40; i++) { const x = -44 + i * 2.2, z = -36 + k * 14 + Math.sin(i * .3 + k) * 4; p.push(V3(x, T.userData.h(x, z) + .3, z)); } L1.add(K.line(p, P.cyan2, .3)); } for (let i = 0; i < 28; i++) { const x = -26 + r() * 52, z = -24 + r() * 48; const f = K.box(1.6 + r(), .35, 1.4 + r(), solid(P.cyan2, P.cyan2, .5, .9)); f.position.set(x, T.userData.h(x, z), z); L1.add(f); } const scan = new THREE.Mesh(new THREE.RingGeometry(0, 34, 96, 1, 0, .8), new THREE.MeshBasicMaterial({ color: P.cyan, transparent: true, opacity: .14, side: THREE.DoubleSide, blending: THREE.AdditiveBlending, depthWrite: false })); scan.rotation.x = -Math.PI / 2; scan.position.y = T.userData.h(0, 0) + .5; L1.add(scan); const sat = sprite(0xffffff, 3, .9); L1.add(sat);
    const L2 = mk(); const pv = K.pv(5, 4, 2.2, 1.8, P.blue); pv.position.set(-22, T.userData.h(-22, -18), -18); L2.add(pv); const flows = []; for (let i = 0; i < 10; i++) { const x = -20 + r() * 40, z = -14 + r() * 30; const f = K.flow([V3(-22, T.userData.h(-22, -18) + 1.6, -18), V3(x, T.userData.h(x, z) + 1, z)], P.cyan2, 1, .15 + r() * .1); L2.add(f); flows.push(f); }
    const L3 = mk(); const bars = K.bars([3, 5.5, 8, 11, 14.5], P.green, 2.6); bars.position.set(14, T.userData.h(14, 22), 22); L3.add(bars); L3.add(K.line([[13, 6, 21], [18, 9, 21], [23, 13, 21], [28, 19, 21]], P.green, .9)); const lb3 = K.label('IRR · NPV · LCOE', '#6ee7b7'); lb3.position.set(12, 21, 21); L3.add(lb3);
    const L4 = mk(); const docs = K.docs(); docs.position.set(-24, T.userData.h(-24, 22) + .5, 22); L4.add(docs);
    return { layers: L, radius: 46, tick(t, dt) { rings.forEach((rg, i) => { const ph = (t * .35 + i * .33) % 1; rg.scale.setScalar(1 + ph * 20); rg.material.opacity = (1 - ph) * .7; }); scan.rotation.z = t * .8; sat.position.set(Math.cos(t * .5) * 40, 26, Math.sin(t * .5) * 40); flows.forEach((f) => f.userData.tick(dt)); bars.userData.tick(t); } }; };
  S['pipe-rural'] = () => { const r = rnd(9), L = [], mk = () => { const g = new THREE.Group(); L.push(g); return g; }; const T = K.terrain(180, 90, 2.4, .04); const L0 = mk(); L0.add(T, K.grid(180, 60, P.cyan, .05)); const cp = []; for (let i = 0; i < 90; i++) { const x = -46 + r() * 92, z = -36 + r() * 72; cp.push(V3(x, T.userData.h(x, z) + .6, z)); } L0.add(new THREE.Points(new THREE.BufferGeometry().setFromPoints(cp), new THREE.PointsMaterial({ color: P.cyan2, size: 1.4, map: glowTex, transparent: true, opacity: .9, blending: THREE.AdditiveBlending, depthWrite: false }))); [[0, 0], [-26, 14], [30, -12]].forEach(([x, z], i) => { const b = K.beam(i ? 14 : 26, i ? P.cyan : P.blue2); b.position.set(x, T.userData.h(x, z), z); L0.add(b); }); const lb0 = K.label('TIER A · 481 HH', '#93c5fd'); lb0.position.set(1.5, 11, 0); L0.add(lb0);
    const L1 = mk(); const hs = []; for (let i = 0; i < 18; i++) { const a = r() * 6.28, d = 6 + r() * 26, x = Math.cos(a) * d, z = Math.sin(a) * d * .75; const h = K.house(3 + r() * 1.8, 2.4 + r() * 1.4, 1.1 + r() * .4, r()); h.position.set(x, T.userData.h(x, z), z); L1.add(h); hs.push(h); } const road = []; for (let i = 0; i <= 30; i++) { const x = -30 + i * 2, z = Math.sin(i * .3) * 5; road.push(V3(x, T.userData.h(x, z) + .1, z)); } L1.add(K.line(road, 0x8fa3bd, .35));
    const L2 = mk(); const pv = K.pv(4, 4, 2.2, 1.8, P.blue); pv.position.set(22, T.userData.h(22, 12), 12); L2.add(pv); const hub = V3(22, T.userData.h(22, 12) + 1.6, 12); const flows = hs.map((h) => { const f = K.flow([hub, V3(h.position.x, h.position.y + 1.5, h.position.z)], P.cyan2, 1, .12 + r() * .1); L2.add(f); return f; }); const disp = []; for (let i = 0; i <= 40; i++) disp.push(V3(-40 + i * 1.6, 6 + Math.max(0, Math.sin(i / 40 * Math.PI)) * 9, 30)); L2.add(K.line(disp, P.blue2, .9)); const lb2 = K.label('24 h DISPATCH · PV 39 kWp · BESS 163 kWh', '#93c5fd'); lb2.position.set(-40, 18, 30); L2.add(lb2);
    const L3 = mk(); const bars = K.bars([4, 8, 13], P.green, 2.6); bars.position.set(-38, T.userData.h(-38, -24), -24); L3.add(bars); const lb3 = K.label('GRANT · DEBT · EQUITY', '#6ee7b7'); lb3.position.set(-40, 18, -24); L3.add(lb3);
    const L4 = mk(); const docs = K.docs(); docs.position.set(30, T.userData.h(30, -26) + .5, -26); L4.add(docs);
    const L5 = mk(); const orbit = K.ring(46, P.green, .006); orbit.position.y = 22; orbit.material.opacity = .35; L5.add(orbit); const sat = sprite(P.green, 4, .95); L5.add(sat); const cone = new THREE.Mesh(new THREE.ConeGeometry(10, 22, 32, 1, true), new THREE.MeshBasicMaterial({ color: P.green, transparent: true, opacity: .08, blending: THREE.AdditiveBlending, depthWrite: false, side: THREE.DoubleSide })); L5.add(cone); const lb5 = K.label('SATELLITE PASS · VERIFIED', '#6ee7b7'); lb5.position.set(-20, 30, -44); L5.add(lb5);
    return { layers: L, radius: 44, tick(t, dt) { flows.forEach((f) => f.userData.tick(dt)); bars.userData.tick(t); const a = t * .45; sat.position.set(Math.cos(a) * 46, 22, Math.sin(a) * 46); cone.position.set(Math.cos(a) * 46 * .5, 11, Math.sin(a) * 46 * .5); cone.lookAt(sat.position); cone.rotateX(-Math.PI / 2); hs.forEach((h, i) => { h.userData.win.material.opacity = .3 + .35 * Math.sin(t * 1.5 + i); }); } }; };

  /* ---------- runtime ---------- */
  const inst = new Map();
  function mount(cv) {
    const name = cv.dataset.holo; if (!S[name]) return;
    let renderer; try { renderer = new THREE.WebGLRenderer({ canvas: cv, antialias: true, alpha: true, powerPreference: 'high-performance' }); } catch (e) { return; }
    renderer.setClearColor(0x000000, 0); renderer.setPixelRatio(Math.min(window.innerWidth < 700 ? 1 : 1.5, window.devicePixelRatio || 1));
    renderer.toneMapping = THREE.ACESFilmicToneMapping; renderer.toneMappingExposure = 1.15;
    const scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(P.bg, .0032);
    scene.add(new THREE.HemisphereLight(0x3b82f6, 0x04060c, .9)); const sun = new THREE.DirectionalLight(0xdbeafe, 1.4); sun.position.set(40, 80, 30); scene.add(sun); const rim = new THREE.DirectionalLight(0x22d3ee, .6); rim.position.set(-60, 30, -40); scene.add(rim);
    const def = S[name](); def.layers.forEach((g) => scene.add(g));
    const cam = new THREE.PerspectiveCamera(36, 1, .1, 1000);
    const st = { cv, renderer, scene, cam, def, t: Math.random() * 50, theta: def.theta == null ? -.6 : def.theta, phi: def.pitch || .78, tTheta: def.theta == null ? -.6 : def.theta, vTheta: 0, drag: false, lx: 0, vis: false, step: cv.dataset.step != null ? +cv.dataset.step : def.layers.length - 1, shown: def.layers.map(() => 1), spin: def.spin || .1, mx: 0, my: 0, W: 0, H: 0 };
    def.layers.forEach((g, i) => { g.visible = i <= st.step; });
    inst.set(cv, st);
    const size = () => { const w = cv.clientWidth, h = cv.clientHeight; if (!w || !h || (w === st.W && h === st.H)) return; st.W = w; st.H = h; renderer.setSize(w, h, false); cam.aspect = w / h; cam.updateProjectionMatrix(); };
    size(); new ResizeObserver(size).observe(cv);
    new IntersectionObserver((e) => { st.vis = e[0].isIntersecting; }).observe(cv);
    cv.style.cursor = 'grab'; cv.style.touchAction = 'pan-y';
    cv.addEventListener('pointerdown', (e) => { st.drag = true; st.lx = e.clientX; cv.style.cursor = 'grabbing'; cv.setPointerCapture(e.pointerId); });
    cv.addEventListener('pointermove', (e) => { const r = cv.getBoundingClientRect(); st.mx = (e.clientX - r.left) / r.width - .5; st.my = (e.clientY - r.top) / r.height - .5; if (!st.drag) return; const dx = e.clientX - st.lx; st.lx = e.clientX; st.tTheta += dx * .008; st.vTheta = dx * .008; });
    const up = () => { st.drag = false; cv.style.cursor = 'grab'; }; cv.addEventListener('pointerup', up); cv.addEventListener('pointercancel', up); cv.addEventListener('pointerleave', () => { st.mx = st.my = 0; });
  }
  function frame(st, dt) {
    st.t += dt; if (!st.drag) { st.tTheta += (reduce ? 0 : st.spin * dt) + st.vTheta; st.vTheta *= .92; } st.theta += (st.tTheta - st.theta) * .12;
    const R = st.def.radius * (st.W / Math.max(1, st.H) < .9 ? 2.9 : 2.25), phi = st.phi + st.my * .2, th = st.theta + st.mx * .15;
    st.cam.position.set(Math.sin(th) * Math.cos(phi) * R, Math.sin(phi) * R + st.def.radius * .1, Math.cos(th) * Math.cos(phi) * R); st.cam.lookAt(0, st.def.radius * .12, 0);
    st.def.layers.forEach((g, i) => { if (i > st.step) { g.visible = false; return; } g.visible = true; if (st.shown[i] < 1) { st.shown[i] = Math.min(1, st.shown[i] + dt * 1.6); const s = .6 + .4 * sm(st.shown[i]); g.scale.setScalar(s); g.position.y = (1 - sm(st.shown[i])) * 6; } else { g.scale.setScalar(1); g.position.y = 0; } });
    if (st.def.tick) st.def.tick(st.t, reduce ? 0 : dt);
    st.renderer.render(st.scene, st.cam);
  }
  let last = performance.now();
  function loop(now) { requestAnimationFrame(loop); const dt = Math.min(.05, (now - last) / 1000); last = now; inst.forEach((st) => { if (st.vis && st.W) frame(st, dt); }); }
  document.querySelectorAll('canvas[data-holo]').forEach(mount); requestAnimationFrame(loop);
  window.Holo = { setStep(cv, i) { const st = inst.get(cv); if (!st) return; if (i !== st.step) { for (let k = st.step + 1; k <= i; k++) st.shown[k] = 0; st.step = i; } }, scenes: S, kit: K };
})();
